### ISSUE TITLE
C# 7 has generic math / `static virtual` interface members.

### ISSUE THREAD

**Issue by CraigStuntz** [leanprover/fp-lean#114]
Please quote the text that is incorrect:

> In C++, Java, C# and Kotlin, multiple implementations of a method are allowed, with differing numbers and types of arguments. The compiler uses the number of arguments and their types to determine which overload was intended.

> Function and operator overloading has a key limitation: polymorphic functions can't restrict their type arguments to types for which a given overload exists. That is, there is no way to write a function that works for any type that has addition defined.

In what way is this incorrect?

[This is not true in (current) C#](https://learn.microsoft.com/en-us/dotnet/standard/generics/math). I would probably suggest just removing C# from the list of languages there as it's not really germane to the point you're making.

**Comment by david-christiansen** [comment]
The issue at hand isn't really overloaded arithmetic per se, it's ad-hoc polymorphism in general. Removing C# would make this more confusing - I need to just find a good example that isn't addition, now that it's been made into an interface.
