### ISSUE TITLE
Except.failure should be Except.error

### ISSUE THREAD

**Issue by CraigStuntz** [leanprover/fp-lean#115]
Please quote the text that is incorrect:

From §5:

> Looking up an out-of-bounds value yields an `Except.failure:`

In what way is this incorrect?

The actual name of the member is `error`:

```lean
inductive Except (ε : Type) (α : Type) where
  | error : ε → Except ε α
  | ok : α → Except ε α
deriving BEq, Hashable, Repr
```

**Comment by david-christiansen** [comment]
Sorry for the late attention - I'm swamped but will fix this when I can.

**Comment by david-christiansen** [comment]
Thanks!
