### ISSUE TITLE
[PR Request] Fix a few typos

### ISSUE THREAD

**Issue by pitmonticone** [leanprover/fp-lean#117]
Given the following statements in the [contribution guidelines](https://github.com/leanprover/fp-lean/blob/master/CONTRIBUTING.md): 
- "If you find a mistake in the book, please open an issue!"
- "Generally speaking, pull requests are not welcome without prior agreement."

I've forked the repository and fixed a few typos [here](https://github.com/pitmonticone/fp-lean) and I would like to ask you wether I'm allowed to open the associated PR or let you copy and paste the corrections from the forked repository. 

Thanks a lot for making such an amazing resource publicly available for free!

**Comment by david-christiansen** [comment]
Hello! Sorry for the slow reply, I've been traveling for work.

I'd really rather avoid PRs to the text (in particular, Microsoft has the copyright and wants contributors to sign a CLA, and it's easier to have a more general "no PRs please" to avoid time-consuming debates about the border between mere typo fixes, style fixes, and more substantive issues).

That said, you've identified three typos. I'll take this as an issue report to be fixed next time I get some time to catch up on this project :-)

> Thanks a lot for making such an amazing resource publicly available for free!

Please send your thanks to Microsoft Research - they made it possible! I'm glad you're finding the book valuable.

**Comment by david-christiansen** [comment]
I've finally got time to revisit the book - thanks again!
