### ISSUE TITLE
[Typo] Two typos

### ISSUE THREAD

**Issue by crvdgc** [leanprover/fp-lean#120]
As per the contribution guideline, I will not submit a PR, but just put here a link to [the commit in a fork](https://github.com/crvdgc/fp-lean/commit/6fbac26f064e8f2b8b9a989086ab6efab2fc6fc9).

Thank you for your amazing work. It's a very enjoyable and eye-opening read.

**Comment by digama0** [comment]
I don't think the second typo is a typo

**Comment by crvdgc** [comment]
> I don't think the second typo is a typo

Thank you for the feedback. From my understanding, this paragraph is talking about something like `natToPos? : Nat → Option Pos`, since the other way is total?

**Comment by david-christiansen** [comment]
That's right - this is why it's not a typo. But the phrasing may be confusing. There's two ways to convert a `Nat` _n_ to a `Pos`: either it is a partial function where `0` is not mapped to a `Pos`, or it maps _n_ to the `Pos` that denotes _n_ + 1. Does that make sense?

I am really busy but will fix these things when I can - thank you!

**Comment by david-christiansen** [comment]
It was indeed a mistake. Sorry for the noise, and thanks for the feedback - it's fixed now
