### ISSUE TITLE
Chapter 8.3 `travelDiary` not present in the text

### ISSUE THREAD

**Issue by crvdgc** [leanprover/fp-lean#121]
Please quote the text that is incorrect:

> The schema `travelDiary` represents the fields that are common to both peak and waterfall. It is certainly a subschema of peak, as shown by this example:

In what way is this incorrect?

The schema `travelDiary` is referred. However, [its definition](https://github.com/leanprover/fp-lean/blob/56422d4a279d6a74dcf6dc1f9eaa84227ea81f0c/examples/Examples/DependentTypes/DB.lean#L195-L196) is not included in the text.

**Comment by david-christiansen** [comment]
Thank you! I'm super busy at the moment, but I will fix this when I'm able.

**Comment by david-christiansen** [comment]
Thanks again!
