### ISSUE TITLE
[Typo] Missing space after variable name

### ISSUE THREAD

**Issue by zhassan-aws** [leanprover/fp-lean#129]
Sorry for the nitpick. There's a missing space in the example in the [Pattern Matching section](https://lean-lang.org/functional_programming_in_lean/getting-to-know/datatypes-and-patterns.html#pattern-matching):

https://github.com/leanprover/fp-lean/blob/63249e9e1d61b5c18c95947d0f5b4eed6ceaa669/examples/Examples/Intro.lean#L474

after the `x`:
```
    { x:= f p.x, y := f p.y }
       ^
       | missing space here
```

**Comment by david-christiansen** [comment]
Thanks!
