### ISSUE TITLE
Japanese translation of this book

### ISSUE THREAD

**Issue by Seasawher** [leanprover/fp-lean#139]
Hello, I am studying the Lean language. I think this is a great book!

I hope many Japanese will read this book.
Would you mind if I make a Japanese translation of this book and make it available to the public?

**Comment by david-christiansen** [comment]
Not at all! The book is licensed under Creative Commons for a reason - as long as you follow those guidelines, you may translate and republish all that you want.

I don't want to end up being responsible for the translation, however. I would greatly appreciate it if your translation made clear that you're the one responsible for maintaining it, and also which version of the book it is a translation of, to help avoid reader confusion.

Thank you!
